name: 'docker build'
description: 'Runs docker build'
inputs:
  bash:
    required: true
    default: 'python TraceDisplay'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/bin/bash'
  args:
    - ${{ inputs.bash }}
  env:
    WALK_PATH: '/github/workspace/artifacts'
