on: [push]

jobs:
  record_trace:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y trace-cmd
          sudo trace-cmd record -e sched echo Hello World
  docker_build_job:
    runs-on: ubuntu-latest
    name: Builds docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker build step
        uses: ./
