on: [push]

jobs:
  docker_build_only_job:
    runs-on: ubuntu-latest
    name: Builds docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        uses: ./
        with:
          bash: ':'
  record_small_sched_trace:
    name: Record small-sched-trace.dat
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y trace-cmd
          sudo trace-cmd record -o small-sched-trace.dat -e sched echo Hello World
      - name: Upload small-sched-trace.dat
        uses: actions/upload-artifact@v1
        with:
          name: small-sched-trace.dat
          path: small-sched-trace.dat
  record_small_full_trace:
    name: Record small-full-trace.dat
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y trace-cmd
          sudo trace-cmd record -o small-full-trace.dat -e * echo Hello World
      - name: Upload small-full-trace.dat
        uses: actions/upload-artifact@v1
        with:
          name: small-full-trace.dat
          path: small-full-trace.dat
  docker_build_job:
    runs-on: ubuntu-latest
    name: Builds and Tests docker image
    needs: [record_small_sched_trace, record_small_full_trace]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download small-sched-trace.dat
        uses: actions/download-artifact@v1
        with:
          name: small-sched-trace.dat
          path: artifacts
      - name: Download small-full-trace.dat
        uses: actions/download-artifact@v1
        with:
          name: small-full-trace.dat
          path: artifacts
      - name: Test TraceDisplay
        uses: ./
        with:
          bash: 'pytest TraceDisplay'
      - name: Test NoteBook
        uses: ./
        with:
          bash: 'jupyter nbconvert --Application.log_level=10 --to html --execute TestTraceDisplay.ipynb --output=artifacts/TestTraceDisplay.html'
      - name: Test InteractiveNoteBook
        uses: ./
        with:
          bash: 'jupyter nbconvert --Application.log_level=10 --to html --execute TestInteractiveTraceDisplay.ipynb --output=artifacts/TestInteractiveTraceDisplay.html'
      - name: Upload small-sched-trace.h5
        uses: actions/upload-artifact@v1
        with:
          name: tests
          path: artifacts
