on: [push]

jobs:
  docker_build_job:
    runs-on: ubuntu-latest
    name: Builds docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker build step
        uses: ./.github/
