on: [push]

jobs:
  record_trace:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y trace-cmd
          sudo trace-cmd record -e sched echo Hello World
      - name: Upload trace.dat
        uses: actions/upload-artifact@v1
        with:
          name: trace.dat
          path: trace.dat
  docker_build_job:
    runs-on: ubuntu-latest
    name: Builds docker image
    needs: record_trace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download trace from job record_trace
        uses: actions/download-artifact@v1
        with:
          name: trace.dat
          path: artifacts/trace.dat
      - name: Docker build
        uses: ./
      - run: find .
      - name: Upload trace.h5
        uses: actions/upload-artifact@v1
        with:
          name: trace.h5
          path: artifacts/trace.h5
  docker_build_only_job:
    runs-on: ubuntu-latest
    name: Builds docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        runs:
          using: 'docker'
          image: 'Dockerfile'
          entrypoint: '/bin/bash'
          args:
